install.sh
regression/acdl/complete-check4/main.c
regression/acdl/complete-check4/test.desc
src/acdl/acdl_domain.cpp
src/acdl/acdl_domain.h
src/acdl/acdl_solver.cpp
src/acdl/acdl_solver.h
src/acdl/note
src/acdl/template_generator_acdl.cpp
src/domains/tpolyhedra_domain.cpp
src/ssa/local_ssa.cpp
src/ssa/local_ssa.h
src/summarizer/preprocessing_util.cpp
src/summarizer/summary_checker_acdl.cpp

Commit summary:
- Provide handle of assumption variables to ACDL solver
- Avoid decisions on "cond" variables associated with assumption statements
- Improved gamma-completeness check implementation 
- Identify potential "non-gamma complete" variables by path sensitive analysis 
- Refine is_complete check by making concrete decisions (eg. x==n) on the set of potential "gamma complete" variables
- Use SAT for deduction over conjunction of SSA and the refined abstract value
- Ignore template generation (sum and difference constraints) over same program variables (eg. x#2,x#3)

improved gamma-completeness check implementation

---

src/acdl/acdl_conflict_graph.cpp
src/acdl/acdl_conflict_graph.h
src/acdl/acdl_domain.cpp
src/acdl/acdl_domain.h
src/acdl/acdl_solver.cpp
src/acdl/acdl_solver.h
src/domains/tpolyhedra_domain.cpp

Wrapper for generalising proof for conflicts using domain operator interface 
- Reason trail data structure for storing the implication reasons in the abstract conflict graph
- Current framework can support generalisation up to last decision level

Generalise proofs using domain operator

---

.travis.yml
regression/heap/list_false/test.desc
regression/heap/list_false_kind/main.c
regression/heap/list_false_kind/test.desc
regression/heap/simple_false/test.desc
regression/heap/simple_false_kind/main.c
regression/heap/simple_false_kind/test.desc
regression/memsafety/simple_false/test.desc
regression/memsafety/simple_true/test.desc
src/2ls/preprocessing_util.cpp
src/domains/strategy_solver_heap_tpolyhedra.h
src/domains/template_generator_base.cpp
src/domains/tpolyhedra_domain.cpp
src/ssa/assignments.cpp
src/ssa/assignments.h
src/ssa/dynobj_instance_analysis.cpp
src/ssa/local_ssa.cpp
src/ssa/malloc_ssa.cpp
src/ssa/malloc_ssa.h
src/ssa/ssa_domain.cpp
src/ssa/ssa_domain.h

Currently, we add object allocation guards to the template row post guard to assure that a field of a dynamic object created within a loop can only be updated if it is allocated (i.e. it does not get a non-deterministic value that comes from the input SSA symbol corresponding to the field).
This PR proposes a simpler check for this, we simply add inequality between the SSA version of the field from the end of the loop and the input version to the template row post-guard.
Example: dynamic_object$0.next#10 != dynamic_object$0.next.
Also, this PR fixes a failing Travis checks by fetching the master branch before the linter script is run.

Replace object allocation guards in templates by a simple inequality

---

src/ssa/local_ssa.cpp
src/ssa/local_ssa.h
src/ssa/malloc_ssa.cpp

Do not reuse a symbolic dereference in case some aliasing object (or a field of an object) has been assigned after the last definition of the symbolic dereference.
Resolves the problem in #128.

Improve checking when a symbolic deref can be reused.

---

src/domains/tpolyhedra_domain.cpp
src/domains/util.cpp
src/domains/util.h

We cannot add a difference template row for two fields of two dynamic objects
allocated at the same allocation site. This is because the combined guard would
never hold since only one of these objects is always allocated.

heap-zones: do not add difference rows for dyn objs from the same malloc

---

regression/heap-data/process_queue/test.desc
src/2ls/2ls_parse_options.cpp
src/2ls/2ls_parse_options.h
src/2ls/preprocessing_util.cpp
src/2ls/version.h
src/domains/tpolyhedra_domain.cpp
src/domains/util.cpp
src/domains/util.h

Difference rows for different instances of the same dynamic object (same allocation site) are forbidden, since two such objects cannot exist simultaneously in a single iteration.

Multiple fixes for SV-COMP

---

src/2ls/2ls_parse_options.cpp
src/2ls/2ls_parse_options.h
src/2ls/horn_encoding.cpp
src/2ls/horn_encoding.h
src/2ls/preprocessing_util.cpp
src/2ls/show.cpp
src/2ls/show.h
src/2ls/version.h
src/domains/template_generator_base.cpp
src/domains/tpolyhedra_domain.cpp
src/domains/util.cpp
src/domains/util.h
src/ssa/assignments.cpp
src/ssa/assignments.h
src/ssa/dynobj_instance_analysis.cpp
src/ssa/dynobj_instance_analysis.h
src/ssa/local_ssa.cpp
src/ssa/local_ssa.h
src/ssa/ssa_db.h
src/ssa/ssa_dereference.cpp
src/ssa/ssa_dereference.h
src/ssa/ssa_value_set.cpp
src/ssa/ssa_value_set.h
src/ssa/unwindable_local_ssa.h

There are multiple things implemented:
- handle comparison of freed pointers
- fix bugs in work with dynamic objects
With these changes, we have no false results in heap-related categories (except for 2 long-known false positives).

Improvements for SV-COMP 2020

---

regression/book-examples/free_safety/memory_safety.desc
regression/book-examples/free_safety/memory_safety_free_error.desc
regression/book-examples/sll_min/assertions.desc
regression/heap-data/calendar/test.desc
regression/heap-data/cart/test.desc
regression/heap-data/hash_fun/test.desc
regression/heap-data/min_max/test.desc
regression/heap-data/packet_filter/test.desc
regression/heap-data/process_queue/test.desc
regression/heap-data/quick_sort_split/test.desc
regression/heap-data/running_example/test.desc
regression/heap-data/running_example_assume/test.desc
regression/heap-data/shared_mem1/test.desc
regression/heap-data/shared_mem2/test.desc
regression/heap/built_from_end/test.desc
regression/heap/dll1_simple/test.desc
regression/heap/list_false/test.desc
regression/heap/list_false_kind/test.desc
regression/heap/list_true/test.desc
regression/heap/simple_false/test.desc
regression/heap/simple_false_kind/test.desc
regression/heap/simple_true/test.desc
regression/heap/sll_rhs_concretisation/test.desc
regression/heap/sll_simple/test.desc
regression/memsafety/built_from_end/test.desc
regression/memsafety/built_from_end_false/test.desc
regression/memsafety/simple_false/test.desc
regression/memsafety/simple_true/test.desc
src/2ls/2ls_parse_options.cpp

We always use `--sympath` and `--inline` with all heap options so it can be run implicitly to improve user experience.

Automatically set --inline and --sympath when --heap* is set

---

src/2ls/preprocessing_util.cpp

Until now, we only handled correct comparison of freed pointers in normal conditions, not in assertions.

Handle comparison of freed pointers in assertions

---

src/2ls/2ls_parse_options.cpp
src/2ls/2ls_parse_options.h
src/2ls/preprocessing_util.cpp
src/2ls/version.h

Backporting changes made for SV-COMP'21:
- disallow calls to `atexit` in competition mode
- update CBMC to a version that contains fixes for witness format
It would be also nice to add tags after the merge (`0.9.1` and `0.9.1-sv-comp-21` or something similar).

SV-COMP'21 backport

---

src/2ls/graphml_witness_ext.cpp
src/2ls/instrument_goto.cpp
src/domains/ssa_analyzer.h
src/domains/template_generator_base.h
src/solver/summarizer_base.cpp
src/solver/summarizer_bw.cpp
src/solver/summarizer_bw.h
src/solver/summarizer_bw_term.cpp
src/solver/summarizer_fw.cpp
src/solver/summarizer_fw_contexts.cpp
src/solver/summarizer_fw_term.cpp
src/solver/summary.h
src/solver/summary_db.cpp
src/solver/summary_db.h
src/ssa/ssa_inliner.cpp

This is a preparation for implementation of GOTO code instrumentation. It will be useful to have access to the whole domain to be able to easily instrument GOTO code with invariants. It was necessary to slightly tweak how summary_db works with summaries (previously, summaries were copied when obtaining them from summary_db, references are returned after the changes).

Store domain and its value in summary

---

regression/memsafety/built_from_end_false/test.desc
regression/memsafety/simple_false/test.desc
src/2ls/2ls_parse_options.cpp
src/2ls/horn_encoding.cpp
src/2ls/preprocessing_util.cpp
src/2ls/show.cpp
src/2ls/summary_checker_base.cpp
src/2ls/version.h
src/ssa/dynobj_instance_analysis.cpp
src/ssa/dynobj_instance_analysis.h
src/ssa/local_ssa.cpp
src/ssa/local_ssa.h
src/ssa/malloc_ssa.cpp
src/ssa/may_alias_analysis.cpp
src/ssa/may_alias_analysis.h
src/ssa/ssa_build_goto_trace.cpp
src/ssa/ssa_db.h
src/ssa/ssa_dereference.cpp
src/ssa/ssa_domain.cpp
src/ssa/ssa_domain.h
src/ssa/ssa_value_set.cpp
src/ssa/ssa_value_set.h
src/ssa/unwindable_local_ssa.h

2 releases at once this time, since 5.10 required only a small test change (see the commit). The next release is probably going to be tough...
CBMC 5.11 most important changes:
- abstract interpretation changes, `transform` now takes function name, `operator()` as well. This required changing the passed arguments to various objects/methods in a lot of places
- `output` method removed from various objects, e.g. from `goto_modelt`, replaced with `show_goto_functions` function
- `lhs_object` has been removed from `goto_step_tracet`, I am not very confident about my fix in https://github.com/diffblue/2ls/commit/b35aedb6e79b66feff3f97004f82ce511b55a240 ...
- `pointer_offset_size` now returns `std::optional`
Related: https://github.com/peterschrammel/cbmc/pull/24

Update to CBMC 5.11

---

.github/workflows/ci.yml

The action would fail after a pull request is merged into master due to the `git fetch` command which refuses to fetch the current branch.

Support linting even from the master branch

---

src/2ls/2ls_parse_options.cpp
src/2ls/cover_goals_ext.cpp
src/2ls/preprocessing_util.cpp
src/2ls/summary_checker_nonterm.cpp
src/config.inc
src/domains/heap_domain.cpp
src/domains/product_domain.cpp
src/domains/product_domain.h
src/domains/simple_domain.h
src/domains/strategy_solver_binsearch3.h
src/domains/tpolyhedra_domain.cpp
src/solver/summarizer_base.cpp
src/solver/summarizer_bw.cpp
src/solver/summarizer_fw_contexts.cpp
src/ssa/address_canonizer.cpp
src/ssa/local_ssa.cpp
src/ssa/ssa_build_goto_trace.cpp
src/ssa/ssa_dereference.cpp
src/ssa/ssa_domain.h
src/ssa/ssa_inliner.cpp
src/ssa/ssa_pointed_objects.cpp
src/ssa/ssa_value_set.cpp
src/ssa/unwindable_local_ssa.h

This PR fixed warnings thrown by gcc and clang and also makes `config.inc` a bit more modular similar to how CBMC does this. Also `-Werror` is now enabled by default.

Fix compilation warnings

---

regression/kiki/hard2_unwindbound5/main.c
regression/kiki/hard2_unwindbound5/test.desc
regression/memsafety/built_from_end/test.desc
regression/memsafety/double_free/main.c
regression/memsafety/double_free/test.desc
regression/memsafety/simple_true/test.desc
regression/preconditions/precond_contextsensitive1/test.desc
src/2ls/2ls_parse_options.cpp
src/2ls/2ls_parse_options.h
src/2ls/preprocessing_util.cpp
src/domains/heap_domain.cpp
src/ssa/dynobj_instance_analysis.cpp
src/ssa/local_ssa.cpp
src/ssa/local_ssa.h
src/ssa/malloc_ssa.cpp
src/ssa/ssa_domain.h
src/ssa/ssa_unwinder.cpp

This implements fixes for problems mostly created during the recent CBMC rebase that were revealed in SV-COMP runs.
These are in particular:
- Fix of `dynobj_instance_analysis` which caused that dynamic objects were never split into multiple instances. This, however, broke heap regression tests.
- Fix usage of allocation guards w.r.t. new `malloc` implementation in CBMC that makes the regression tests work again.
- Fix collection of `record::free` vars w.r.t. new `free` implementation.
- Drop conditional update of dynamic objects which caused some false positive results (due to over-approximation) and which shouldn't be necessary since we use dynamic object instances (that should guarantee soundness).
- Improve resolution of pointed-to objects obtained from the solver in heap domain.
- …

SV-COMP fixes

---

src/2ls/2ls_parse_options.cpp
src/domains/heap_domain.cpp
src/domains/heap_domain.h
src/domains/template_generator_base.cpp
src/ssa/dynamic_objects.cpp
src/ssa/dynamic_objects.h
src/ssa/local_ssa.cpp

Originally, symbolic paths were meant to handle the situation when a heap invariant containing addresses of dynamic objects would be used for cases when the dynamic objects were not allocated.
Thanks to the new dynamic object management class, this problem can be solved in a better way by adding a loop guard (guarding the object allocation) directly to the heap invariant. In particular, if a heap template row value contains a pointer-object equality (stating that the pointer may point to the object), this adds (conjuncts) a loop-select guard of the object allocation loop.
For example, if the original row value was e.g.:
```    
p#lb50 == &dynamic_object$16 || p#lb50 == &dynamic_object$32
``` 
where `dynamic_object$16` is allocated in a loop with `$guard#ls30` and `dynamic_object$32` is …

Drop symbolic path domain

---

.clang-format
.github/workflows/ci.yml
regression/.clang-format
src/2ls/2ls_parse_options.cpp
src/2ls/2ls_parse_options.h

Using `.clang-format` from CBMC with one tweak:
- `AlignAfterOpenBracket` is set to `Align` (instead of `AlwaysBreak`) as the old option would put a break after the opening bracket in a multiline if, which looks ugly
The formatting is turned off for regression tests, help, and CLI options list.
Instead of reformatting the entire codebase with `clang-format`, we use the `git-clang-format` tool to run the checks on changed lines only for each PR.
I've tested this on the array work which I'll post in a following PR, with the new style. At the moment, it's in my [arrays](https://github.com/viktormalik/2ls/tree/arrays) branch (to preview the new style).
Closes #165.

Start using clang-format to format code

---

regression/heap/sll_circular_traversal/main.c
regression/heap/sll_circular_traversal/test.desc
src/ssa/goto_unwinder.cpp

Commit 89e30e27 replaced usage of the `#malloc_result` property by querying the dynamic objects database. This is not sufficient for the GOTO unwinder since it used to use that property to locate the cloned malloc instruction (already containing the generated dynamic objects). As the GOTO unwinder does not duplicate entries in the dynamic objects database, the malloc location is now not identified properly.
This fixes the above problem by introducing a `#malloc` property, local to the unwinder, which we use to mark the malloc result instruction prior to running the CBMC unwinder. Since properties are cloned during unwinding, we can use it to locate the new malloc instruction and properly generate new dynamic objects.
Add test from SV-COMP which contains a linked list of a fixed length, so …

Fix GOTO undinwing of dynamic objects

---

regression/heap/symderef_reuse/main.c
regression/heap/symderef_reuse/test.desc
src/ssa/local_ssa.cpp

We allow to reuse symbolic dereference objects to increase precision of the verification. One of the conditions for the reuse is that the dereferenced pointer must not have been overridden from the point of the last symbolic deref definition.
This condition contains a bug, though, as it assumed that the last definition is always an assignment. With unwinding in place, it can also be a phi instruction, so this commit adds that possibility.
Contains also a reproducer regression test.

Fix bug in reusing symbolic dereferences

---

src/ssa/ssa_build_goto_trace.cpp

Previously, the function was not set which resulted in an empty "assumption.scope" tag, the XML library converted it to a singular tag, while as per the specification, it must be dual, causing witnesslint to fail.

Set function on GOTO trace

---

src/domains/array_domain.cpp
src/domains/strategy_solver_binsearch.cpp
src/domains/template_generator_base.cpp
src/domains/template_generator_base.h

When `--std-invariants` is set, invariants are computed for the loop head (i.e. contain the pre-loop value in addition to the loop-back values). This is not convenient for arrays since they are typically uninitialized and only get initialized inside a loop. Including the pre-loop array value would add the nondet value to the invariant, making the entire invariant (especially the one for the initializer loop) nondet.
This change prohibits usage of standard invariants for the array domain. Most of the changes are done in the template generator which:
- does not generate aux_expr for array var specs,
- always passes post_renaming_map (instead of aux_renaming_map) to the array domain and its inner domains.
This is especially necessary for SV-COMP where we use `--k-induction` which sets …

Support arrays with standard invariants

---

regression/heap-data/shared_mem1_false/test.desc
regression/kiki/hard2_unwindbound5/test.desc
regression/kiki/induction5/test.desc
regression/kiki/induction7/test.desc
regression/kiki/nested12/test.desc
regression/overflows/Makefile
regression/overflows/scanf-overflow-bad/main.c
regression/overflows/scanf-overflow-bad/test.desc
regression/overflows/scanf-overflow-good/main.c
regression/overflows/scanf-overflow-good/test.desc
src/2ls/2ls_parse_options.cpp
src/2ls/2ls_parse_options.h
src/2ls/preprocessing_util.cpp
src/2ls/summary_checker_kind.cpp
src/domains/array_domain.cpp
src/domains/array_domain.h
src/domains/template_generator_base.cpp
src/ssa/local_ssa.cpp

List of changes:
- Support combination of `--values-refine` and `--k-induction` - so far, we supported `--values-refine` for AI only, which was fine since it was needed for heap for which we disabled k-induction. Now with the new unwinding, we need to support `--values-refine` for k-induction, too.
- Disable `--std-invariants` for `--k-induction` as it causes more problems than just for the array invariants (fixed in #171). It also makes heap-data examples not to pass.
- Make user inputs (from `*scanf` calls) non-deterministic.
- Fixes for dynamic object splitting, array domain template, and witness generation

Several fixes for SV-COMP
